add _66.java solution2
fishercoder1534/Leetcode pull request #116
Opened 2020-10-24 07:05 UTC by WillShen7789

2020-10-24 08:33 UTC, yaodehaung commented
@WillShen7789 great

2020-10-24 15:28 UTC, fishercoder1534 requested changes

2020-10-24 15:28 UTC, fishercoder1534 commented on src/test/java/com/fishercoder/_66Test.java
> +import com.fishercoder.solutions._1005;
why here?

2020-10-24 15:28 UTC, fishercoder1534 commented on src/test/java/com/fishercoder/_66Test.java
> +        digits = new int[]{9, 9, 9, 9};
Please write new tests for `solution2` so each test is responsible for only one solution. Thanks

2020-10-24 17:57 UTC, WillShen7789 commented on src/test/java/com/fishercoder/_66Test.java
> +import com.fishercoder.solutions._1005;
My mistake.

2020-10-25 06:36 UTC, WillShen7789 commented
1.write new tests for solution2
2.remove import

2020-10-25 16:19 UTC, fishercoder1534 approved these changes

2020-10-25 16:19 UTC, merged