feat: add _747.js
fishercoder1534/Leetcode pull request #117
Opened 2020-10-24 15:43 UTC by yaodehaung

2020-10-24 15:49 UTC, fishercoder1534 requested changes

2020-10-24 15:49 UTC, fishercoder1534 commented on javascript/_747.js
> +
Remove this empty line.

2020-10-24 15:49 UTC, fishercoder1534 commented on javascript/_747.js
> +
Ditto.

2020-10-24 15:49 UTC, fishercoder1534 commented on javascript/_747.js
> +      var maxdata = -1;
Indentation line up please.

2020-10-24 16:28 UTC, yaodehaung commented on javascript/_747.js
> +      var maxdata = -1;
ok

2020-10-26 01:07 UTC, yaodehaung commented
I solved the problem.

2020-10-27 14:32 UTC, WillShen7789 commented
good js

2020-12-19 09:28 UTC, closed without merging