Add solution for problem 1658 in javascript
fishercoder1534/Leetcode pull request #136
Opened 2020-11-19 01:02 UTC by ltp88

2020-11-19 15:37 UTC, fishercoder1534 requested changes
Did you miss the actual file?

2020-11-19 15:44 UTC, ltp88 commented
OMG! I forgot to add the file.
I just add the file.

2020-11-19 15:51 UTC, ltp88 commented
I added the file, please review when u can.

2020-11-20 01:21 UTC, ltp88 reviewed
added file

2020-11-23 11:15 UTC, closed without merging